### ISSUE TITLE
How do I update npackd?

### ISSUE THREAD

**Issue by binki** [tim-lebedkov/npackd-cpp#4]
I see “NPackd-1.22.2” listed in Npackd GUI but it doesn’t seem to recognize that I already have NPackd-1.21.6 installed already. Also, I recall trying to update NPackd from within itself in the past and it not seeming to work perfectly. And, also, the [readme](README.md) still seems to have instructions for installing 1.21.6 instead of 1.22.2.

What is the intended way for upgrading? Is it a manual process and, if so, where are the instructions?

**Comment by tim-lebedkov** [comment]
Npackd since 1.21 cannot update itself if it was installed via an .msi. The actual problem is that it cannot recognize the installed program as Npackd.

This should get better in the next version.

What is currently possible is to download a .zip, start Npackd and install Npackd. After this is done, you can update Npackd and it works pretty good.

I will update the readme.
