### ISSUE TITLE
scan multiple folders

### ISSUE THREAD

**Issue by tim-lebedkov** [tim-lebedkov/npackd-cpp#54]
> 
> 
> you can change the installation directory anytime. This does not affect the previous installations.
> 
> Example:
> 
>     1. set installation directory to "C:\Program Files"
> 
>     2. install "Notepad++" => it will be in "C:\Program Files\Notepad++"
> 
>     3. set installation directory to "D:\Programs"
> 
>     4. install "Firefox" => it will be in "D:\Programs\Firefox". "Notepad++" will still be in "C:\Program Files\Notepad++" and Npackd will know that.

This trick does not work for freshly installed npackd. i have so many apps under portableapps folder, and npackd is unable to scan that folder. Can you add "scan multiple folder" feature to installation directory? (separated by semicolon may be)

_Originally posted by @the-liquid-metal in https://github.com/tim-lebedkov/npackd/issues/536#issuecomment-655770085_

**Comment by tim-lebedkov** [comment]
Are these real PortableApps.com (or similar) programs? Is your plan to use Npackd instead or in parallel?

**Comment by the-liquid-metal** [comment]
I am still evaluating Npackd. As a chocolatey user, Npackd is simpler and lighter compared to chocolatey. And I was impressed by the ease with which people added new applications: there's no need to know powershell.

> Are these real PortableApps.com (or similar) programs? Is your plan to use Npackd instead or in parallel?

Yes, those are PortableApps.com apps. Plus many portable apps which comply with their spec but distributed by the original author (i.e. not listed on PortableApps.com). And I made my own portable app version that was originally distributed not as a portable app. These two, i have to check, download, and update manually.

I am using chocolatey to cover up this problem. But this is not a perfect solution. Some apps installed with it's version string attached to it's folder. so i have to recreate symlink in order to maintain interoperability between chocolatey and PortableApps.com.

All my apps are functioning properly. But chocolatey thinks there is a dependency problem and tries to solve it with its own solution. So it installs identical runtime or other apps which i have never used, and it eats up my space.

Interoperability between PortableApps.com and other package manager is just a matter of replacing old ```MyApp``` folder in ``` %PORTABLEAPPS%\MyAppPortable\App\MyApp``` with a new one. And if i am not lucky, i have to delete ```MyApp``` manually and symlink it to where the new version is installed: ```mklink /D  %PORTABLEAPPS%\MyAppPortable\App\MyApp "%PROGRAMFILES%\MyApp"```. But this step only once.

Hopefully, Npackd is flexible enough to be able to tandem with Portable App.com.

**Comment by tim-lebedkov** [comment]
Currently there are only a few third party package managers supported by Npackd: software from the control panel, MSI packages, etc. It is unlikely there will be one for PortableApps.com (at least soon).

You can register existing packages in Npackd via the command line:

``
ncl place --package <package>
            --version <version> --file <directory>
            [--bare-format | --json]
``
